### ISSUE TITLE
Debug.Assert doesn't work in Unity

### ISSUE THREAD

**Issue by jkeon** [decline-cookies/anvil-unity-core#30]
Debug.Assert doesn't actually do anything because the required compiler flags don't exist. 

Need a way to have those present in the Editor and Developer builds.

**Comment by tjvezina** [comment]
Returning to the original issue, `System.Diagnostics.Debug.Assert(...)` doesn't seem to work in Unity, so any uses in `anvil-csharp-core` fail to log messages, throw exceptions, or halt execution when triggered. I think the screenshot above was using `UnityEngine.Debug.Assert(...)`.

It's impossible to find information about this online - the solution is always "just use Unity's Debug.Assert", or Google assumes that's what you're looking up in the first place. The only option for non-Unity code appears to be explicitly throwing an exception when an if-check fails.

**Comment by jkeon** [comment]
I haven't looked into this in any depth (https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview). I know ECS/DOTS is heavily using source generators to make things behind the scenes. 

What would be awesome for Anvil is to have a way to write (all names etc TBD)

`AnvilDebug.Assert(condition, $"Message with {context} variables {inline}")`

Super quick and simple to write out. 

The source generator picks that up and extracts it to:

```
AnvilAssert1(context1, context2);

#if DEBUG
[Conditional("DEBUG")] //This flag is based on the type of Assert "Debug.Assert vs Trace.Assert or whatever we invent"
private void AnvilAssert1(var context1, var context2)
{
        if (!condition)
        {
                return;
        }
        throw new Exception($"Message with {context1} and {context2});
}
#endif
```

- You'd get the ease of use as a dev to write quick safety checks. 
- When running in a build without the flag, the callsite and implementation are stripped so no perf hit.
- When running in editor or build with the flag we still get the safety but no perf hit with allocating strings that are never used.

**Comment by mbaker3** [comment]
See this post. Seems like we just need to set up a `TraceListener`?
https://forum.unity.com/threads/assert-in-unity3d.44513/#post-1860374

This is worth exploring before going down the path of source generation.

**Comment by jkeon** [comment]
Oh yeah! I forgot about those too. We extended one in a console project last year. That might work really well. Good catch @mbaker3

**Comment by tjvezina** [comment]
On `System.Diagnostics.Debug.Assert(...)` failure, should the listener throw an exception or just `Debug.LogError(...)`? I think the former is what I'd expect and allows catching the exception, but the latter doesn't halt execultion.

**Comment by jkeon** [comment]
In my opinion I think it should throw an exception. If an Assert gets triggered, something bad happened and you can't really trust the state of the entire app after that so we should halt and the dev fixes it. 

OR in the rare case where an error could happen that is ok, then the dev can wrap in a try/catch and deal with it gracefully. 

`Debug.LogError` in my mind feels more like a way to easily color-code the log in Unity.

**Comment by mbaker3** [comment]
We should probably just match whatever `UnityEngine.Debug.Assert()` does. Maybe even pass the error along to that method?

If that's not a good idea then I'm in the exception camp. Maybe there's an Assertion specific exception we can throw.

**Comment by tjvezina** [comment]
Annoyingly, `UnityEngine.Debug.Assert(...)` seems to simply log an error, no thrown exceptions.
`UnityEngine.Assertions.Assert.IsTrue(...)` does however.

Either way I agree that it should throw an exception, and will keep it doing so directly.
